//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softplan.Common.Messaging.RabbitMq.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Softplan.Common.Messaging.RabbitMq.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Creating a new API Manager instance.&quot;.
        /// </summary>
        public static string APIManagerCreating {
            get {
                return ResourceManager.GetString("APIManagerCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Consumer já iniciado.&quot;.
        /// </summary>
        public static string ConsumerAlreadyStarted {
            get {
                return ResourceManager.GetString("ConsumerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination cannot be empty..
        /// </summary>
        public static string MessageDestionationIsNull {
            get {
                return ResourceManager.GetString("MessageDestionationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Não existe nenhuma mensagem mapeada para a fila {0}.&quot;.
        /// </summary>
        public static string NoMessagesMappedToQueue {
            get {
                return ResourceManager.GetString("NoMessagesMappedToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da fila não informado..
        /// </summary>
        public static string QueueNameNotFound {
            get {
                return ResourceManager.GetString("QueueNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao consultar API do RabbitMQ. Status {0} - {1}..
        /// </summary>
        public static string RabbitMQAPIError {
            get {
                return ResourceManager.GetString("RabbitMQAPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resposta da mensagem não foi recebida..
        /// </summary>
        public static string ReplyMessageNotReceived {
            get {
                return ResourceManager.GetString("ReplyMessageNotReceived", resourceCulture);
            }
        }
    }
}
