//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElasticApmPublisherSample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElasticApmPublisherSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;1&apos; to send a message or &apos;2&apos; to send a message and wait response..
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application closed..
        /// </summary>
        public static string ApplicationClosed {
            get {
                return ResourceManager.GetString("ApplicationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops. Some problem occurred...
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;c&apos; to close or any key to send other message..
        /// </summary>
        public static string ClosingApplication {
            get {
                return ResourceManager.GetString("ClosingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to calc fibonacci to {0}..
        /// </summary>
        public static string FibonacciError {
            get {
                return ResourceManager.GetString("FibonacciError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci to {0} is {1}..
        /// </summary>
        public static string FibonacciResult {
            get {
                return ResourceManager.GetString("FibonacciResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid integer..
        /// </summary>
        public static string InvalidIntValue {
            get {
                return ResourceManager.GetString("InvalidIntValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing message..
        /// </summary>
        public static string MessageHandlingError {
            get {
                return ResourceManager.GetString("MessageHandlingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message successfully processed..
        /// </summary>
        public static string MessageSuccessfullyProcessed {
            get {
                return ResourceManager.GetString("MessageSuccessfullyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing message..
        /// </summary>
        public static string PublishingMessage {
            get {
                return ResourceManager.GetString("PublishingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response received..
        /// </summary>
        public static string ResponseReceived {
            get {
                return ResourceManager.GetString("ResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Apm agent configuration..
        /// </summary>
        public static string SettingApmAgentConfiguration {
            get {
                return ResourceManager.GetString("SettingApmAgentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting application..
        /// </summary>
        public static string StartingApplication {
            get {
                return ResourceManager.GetString("StartingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;c&apos; to close application or any number to calc Fibonacci..
        /// </summary>
        public static string WaitingFibonacciNumber {
            get {
                return ResourceManager.GetString("WaitingFibonacciNumber", resourceCulture);
            }
        }
    }
}
